# Generated by Django 5.0.3 on 2024-03-14 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="element",
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("project_id", models.IntegerField()),
                ("element", models.CharField(max_length=50)),
                ("element_id", models.CharField(max_length=50)),
                ("position", models.IntegerField()),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Element",
        ),
        migrations.DeleteModel(
            name="Property",
        ),
    ]
